from __future__ import annotations

from types import MappingProxyType
from typing import Final

from phatch.lib.reverse_translation import _t

_HELP_GROUPS: Final = (
    (
        _t("Choose the operation or behavior used by this action."),
        ("Action", "Method", "Mode", "Transformation", "Utility"),
    ),
    (_t("Set how strongly the result blends with the original."), ("Amount",)),
    (
        _t("Set the horizontal placement from the left edge."),
        ("Align Horizontal", "Horizontal Justification", "Horizontal Offset", "Left"),
    ),
    (
        _t("Set the vertical placement from the top edge."),
        ("Align Vertical", "Top", "Vertical Justification", "Vertical Offset"),
    ),
    (_t("Apply the same inset to every edge."), ("All",)),
    (
        _t("Allow this action to be the final action in the list."),
        ("Allow as last action",),
    ),
    (_t("Set the rotation angle."), ("Angle", "Blur Angle", "Sketch Angle")),
    (_t("Choose the output image format."), ("As",)),
    (_t("Remove transparent outer pixels after processing."), ("Auto Crop",)),
    (
        _t("Choose how the rendered background is filled."),
        ("Background", "Fill", "Fill Type"),
    ),
    (_t("Choose the color placed behind the image."), ("Background Color",)),
    (_t("Set the transparency of the generated background."), ("Background Opacity",)),
    (_t("Set the number of color bits retained per channel."), ("Bits",)),
    (_t("Choose the color representing the darkest input values."), ("Black",)),
    (_t("Allow content to extend beyond the target crop before fitting."), ("Bleed",)),
    (_t("Set the radius used by the blur operation."), ("Blur Radius",)),
    (_t("Enable blur on the reflected image."), ("Blur Reflection",)),
    (_t("Set the Gaussian spread used by the blur operation."), ("Blur Sigma",)),
    (_t("Set the padding around the generated shadow."), ("Border",)),
    (_t("Choose the color of the image border."), ("Border Color",)),
    (_t("Set the thickness of the border on every edge."), ("Border Width",)),
    (_t("Set the inset from the bottom edge."), ("Bottom",)),
    (_t("Choose the treatment for the bottom-left corner."), ("Bottom Left Corner",)),
    (_t("Choose the treatment for the bottom-right corner."), ("Bottom Right Corner",)),
    (
        _t("Set the perspective factor applied to the bottom edge."),
        ("Bottom Shear Factor",),
    ),
    (_t("Choose the color of the rendered box."), ("Box Color",)),
    (_t("Set the depth of the rendered box."), ("Box Depth",)),
    (_t("Increase the brightness of the midtones."), ("Brighten",)),
    (_t("Choose a packaged camera angle or enter a custom camera."), ("Camera",)),
    (_t("Set the camera distance from the rendered object."), ("Camera Distance",)),
    (
        _t("Set the camera rotation around the vertical axis."),
        ("Camera Horizontal Rotation",),
    ),
    (_t("Set the camera field-of-view lens angle."), ("Camera Lens Angle",)),
    (_t("Set the camera roll around its viewing axis."), ("Camera Roll",)),
    (_t("Set the camera elevation angle."), ("Camera Vertical Rotation",)),
    (_t("Set the target canvas height."), ("Canvas Height", "Render Height")),
    (_t("Set the target canvas width."), ("Canvas Width", "Render Width")),
    (_t("Set text rendered beneath the generated image."), ("Caption",)),
    (_t("Choose which timestamps are changed."), ("Change",)),
    (_t("Set the radius used by the charcoal effect."), ("Charcoal Radius",)),
    (_t("Choose the primary color for this operation."), ("Color", "Color Value")),
    (_t("Set the width of lines between image columns."), ("Column Line Width",)),
    (_t("Set the number of image columns."), ("Columns",)),
    (
        _t("Enter the external command template and its file placeholders."),
        ("Command",),
    ),
    (
        _t("Keep width and height in the original proportion."),
        ("Constrain Proportions",),
    ),
    (_t("Choose the color used to draw detected contours."), ("Contour Color",)),
    (_t("Set the strength of the contrast curve."), ("Contrast Factor",)),
    (_t("Set the midpoint of the contrast curve."), ("Contrast Treshold",)),
    (_t("Choose which metadata segments are copied."), ("Copy",)),
    (_t("Choose the color of the book cover."), ("Cover Color",)),
    (_t("Set the percentage of extreme pixels ignored by auto contrast."), ("Cutoff",)),
    (_t("Shift the timestamp by this many days."), ("Days",)),
    (_t("Set the height of the reflected region."), ("Depth",)),
    (_t("Set the amount of detail retained by the sketch."), ("Details Degree",)),
    (_t("Choose the direction of the operation."), ("Direction",)),
    (_t("Expand the canvas to contain the rotated image."), ("Expand",)),
    (_t("Set the output name without a file extension."), ("File Name",)),
    (_t("Choose the color used inside the contour."), ("Fill Color",)),
    (_t("Choose a folder containing mosaic fill images."), ("Fill Folder",)),
    (_t("Choose the image used to fill the mosaic."), ("Fill Image",)),
    (_t("Choose the Pillow image effect."), ("Filter",)),
    (_t("Choose the color of the rendered floor."), ("Floor Color",)),
    (_t("Set the transparency of the rendered floor."), ("Floor Opacity",)),
    (
        _t("Set how strongly the rendered floor reflects the object."),
        ("Floor Reflection",),
    ),
    (_t("Choose the font file used to draw text."), ("Font",)),
    (
        _t("Replace transparent pixels with the selected background color."),
        ("Force Background Color",),
    ),
    (_t("Choose the source EXIF or IPTC tag."), ("From (Exif, Iptc)",)),
    (_t("Choose the GPX file containing GPS samples."), ("GPS Data (gpx)",)),
    (
        _t("Choose an optional CSV file for unmatched GPS records."),
        ("GPS Report (csv)",),
    ),
    (_t("Set the empty space between the image and its reflection."), ("Gap",)),
    (_t("Choose the color at the bottom of the gradient."), ("Gradient Bottom",)),
    (_t("Choose the color at the top of the gradient."), ("Gradient Top",)),
    (_t("Choose the highlight image overlaid on the photo."), ("Highlight",)),
    (_t("Shift the timestamp by this many hours."), ("Hours",)),
    (_t("Choose how the source image fits the rendered object."), ("Image Size",)),
    (_t("Choose the destination folder."), ("In",)),
    (_t("Keep the source image visible beneath the contour."), ("Include image",)),
    (_t("Set the JPEG encoding quality."), ("JPEG Quality",)),
    (
        _t("Set the maximum JPEG file size; zero disables the limit."),
        ("JPEG Size Maximum",),
    ),
    (
        _t("Set the accepted difference from the requested JPEG size."),
        ("JPEG Size Tolerance",),
    ),
    (_t("Choose the second image used for the left book page."), ("Left Page",)),
    (_t("Set the perspective shear angle at the left edge."), ("Left Shear Angle",)),
    (_t("Set the rotation of the rendered disc lid."), ("Lid Rotation",)),
    (_t("Choose the color of grid separator lines."), ("Line Color",)),
    (_t("Set the transparency of grid separator lines."), ("Line Opacity",)),
    (_t("Choose the image used as the stamp or watermark."), ("Mark",)),
    (_t("Choose the mask image used to shape transparency."), ("Mask",)),
    (_t("Preserve supported EXIF and IPTC metadata."), ("Metadata",)),
    (_t("Choose the color applied to image midtones."), ("Midtone",)),
    (_t("Shift the timestamp by this many minutes."), ("Minutes",)),
    (_t("Add mist to the rendered background."), ("Mist",)),
    (_t("Shift the timestamp by this many months."), ("Months",)),
    (_t("Choose the three-dimensional object to render."), ("Object",)),
    (_t("Set a shared distance from a non-centered edge."), ("Offset",)),
    (_t("Set the transparency of this layer or effect."), ("Opacity",)),
    (_t("Choose the image orientation applied before placement."), ("Orientation",)),
    (_t("Optimize PNG output for file size."), ("PNG Optimize",)),
    (
        _t("Choose whether one image wraps both pages or pages use separate images."),
        ("Page Mapping",),
    ),
    (_t("Set the radius used by the paint effect."), ("Paint Radius",)),
    (_t("Choose a standard placement or custom offsets."), ("Position",)),
    (_t("Keep the source file modification time."), ("Preserve Timestamp",)),
    (
        _t("Choose a packaged perspective projection or user-defined values."),
        ("Projection",),
    ),
    (_t("Set the radius of the filter or rounded corner."), ("Radius",)),
    (_t("Set which ordered value the rank filter selects."), ("Rank",)),
    (_t("Set how many times the effect is applied."), ("Repeat",)),
    (
        _t("Choose the resampling filter for the highlight image."),
        ("Resample Highlight",),
    ),
    (_t("Choose the resampling filter for resized pixels."), ("Resample Image",)),
    (_t("Choose the resampling filter for the mask image."), ("Resample Mask",)),
    (_t("Set the image resolution in dots per inch."), ("Resolution",)),
    (_t("Set the inset from the right edge."), ("Right",)),
    (
        _t("Set the perspective factor applied to the right edge."),
        ("Right Shear Factor",),
    ),
    (_t("Set the width of lines between image rows."), ("Row Line Width",)),
    (_t("Set the number of image rows."), ("Rows",)),
    (
        _t("Use one corner method for all four corners."),
        ("Same Method for All Corners",),
    ),
    (_t("Set the perspective output scale."), ("Scale",)),
    (_t("Prevent enlargement when the source already fits."), ("Scale Down Only",)),
    (_t("Choose the filter used to resize the reflection."), ("Scale Method",)),
    (_t("Resize the reflection before composing it."), ("Scale Reflection",)),
    (
        _t("Resize grid cells so the final image dimensions stay unchanged."),
        ("Scale to Keep Size",),
    ),
    (
        _t("Shift the timestamp by this many seconds."),
        ("Seconds", "Time Shift (seconds)"),
    ),
    (_t("Choose how the transparent color is detected."), ("Select Color By",)),
    (_t("Set the blur radius of the generated shadow."), ("Shadow Blur",)),
    (_t("Choose the color of the generated shadow."), ("Shadow Color",)),
    (_t("Set the radius used by the sharpen operation."), ("Sharpen Radius",)),
    (_t("Set the Gaussian spread used by the sharpen operation."), ("Sharpen Sigma",)),
    (_t("Reveal advanced lossless-JPEG options."), ("Show Advanced Options",)),
    (_t("Reveal controls for the rendered background."), ("Show Background Options",)),
    (_t("Reveal controls for the rendered floor."), ("Show Floor Options",)),
    (_t("Reveal options for the selected output format."), ("Show Type Options",)),
    (_t("Set the size of the generated detail in image units."), ("Size",)),
    (_t("Set the angle used by the pencil-sketch effect."), ("Sketch Angle",)),
    (_t("Set the radius used by the pencil-sketch effect."), ("Sketch Radius",)),
    (
        _t("Set the Gaussian spread used by the pencil-sketch effect."),
        ("Sketch Sigma",),
    ),
    (_t("Add stars to the rendered background."), ("Stars",)),
    (_t("Choose the color of rendered stars."), ("Stars Color",)),
    (_t("Choose the TIFF compression method."), ("TIFF Compression",)),
    (_t("Choose the EXIF or IPTC tag to remove."), ("Tag",)),
    (_t("Choose the EXIF or IPTC tag to write."), ("Tag (Exif, Iptc)",)),
    (_t("Enter the text or metadata template drawn on the image."), ("Text",)),
    (_t("Choose the destination EXIF or IPTC tag."), ("To (Exif, Iptc)",)),
    (_t("Choose the treatment for the top-left corner."), ("Top Left Corner",)),
    (_t("Choose the treatment for the top-right corner."), ("Top Right Corner",)),
    (_t("Set the perspective shear angle at the top edge."), ("Top Shear Angle",)),
    (
        _t("Place the rendered background on a transparent canvas."),
        ("Transparent Background",),
    ),
    (_t("Choose an optional transpose applied with the projection."), ("Transpose",)),
    (_t("Set the luminance threshold used by solarize."), ("Treshold",)),
    (_t("Set the radius used by the unsharp-mask operation."), ("Unsharp Radius",)),
    (
        _t("Set the Gaussian spread used by the unsharp-mask operation."),
        ("Unsharp Sigma",),
    ),
    (
        _t("Update the EXIF thumbnail during lossless transformation."),
        ("Update Exif Thumbnail",),
    ),
    (_t("Update JPEG image data during lossless transformation."), ("Update JPEG",)),
    (
        _t("Update the EXIF orientation tag after transformation."),
        ("Update Orientation Tag",),
    ),
    (_t("Render a floor beneath the object."), ("Use Floor",)),
    (
        _t("Use the EXIF timestamp as the starting date when available."),
        ("Use exif datetime",),
    ),
    (_t("Enter the value stored in the selected metadata tag."), ("Value",)),
    (_t("Require an input-file placeholder in the command."), ("Verify Input",)),
    (_t("Require an output-file placeholder in the command."), ("Verify Output",)),
    (_t("Require the command executable to be available."), ("Verify Program",)),
    (_t("Set the height of the generated wave."), ("Wave Height",)),
    (_t("Set the wavelength of the generated wave."), ("Wave Length",)),
    (_t("Choose the color representing the lightest input values."), ("White",)),
    (_t("Shift the timestamp by this many years."), ("Years",)),
)


FIELD_HELP: Final = MappingProxyType(
    {label: help_text for help_text, labels in _HELP_GROUPS for label in labels}
)
